Added class Minutes and MinutesTest
manganian/Java23 pull request #11
Opened 2021-09-03 19:09 UTC by manganian

W testach brakuje mi sytuacji, w której przekroczony zostanie zakres int. Można zrobić long, ale co po przekroczeniu zakresu?

2021-09-04 07:52 UTC, MateuszMarczak commented on src/main/java/pl/chojnacki/lesson3/homework/Minutes.java
> +    public static String convertMinutestoSeconds(int minutes) {
Przy konwersji na sekundy oczekiwałbym raczej int niż Stringa.

2021-09-04 07:57 UTC, MateuszMarczak commented
Można zmienić na longa ale nawet przy integerze mamy zakres do ok 35 791 394 minut.  Myślę, że jest wystarczający :)

2021-09-04 07:59 UTC, MateuszMarczak requested changes
Niech metoda zwraca po prostu inta z liczba sekund zamiast Stringa z opisem

2021-09-05 19:30 UTC, mtszpater approved these changes

2021-09-10 10:56 UTC, merged