Added class RectangularTriangle and Test class for it
manganian/Java23 pull request #12
Opened 2021-09-03 21:01 UTC by manganian

2021-09-04 08:09 UTC, MateuszMarczak commented on src/test/java/pl/chojnacki/lesson3/homework/RectangularTriangleTest.java
> +        double A = 3.3;
zmienne nazywamy z małej litery

2021-09-04 08:11 UTC, MateuszMarczak commented on src/main/java/pl/chojnacki/lesson3/homework/RectangularTriangle.java
> +        return sideA * sideA + sideB * sideB == sideC * sideC && sideA > 0 && sideB > 0 && sideC > 0;
trochę bym to uporządkował, bo teraz jak na to patrzę, to zastanawiam się co jest sprawdzane :)

2021-09-04 08:15 UTC, MateuszMarczak requested changes
Możemy popracowac nad czytelnościa w metodzie, może najpierw if sprawdzający czy parametry są dodatnie a następnie dopiero a2+b2=c2. Sprawdźmy również standardową bibliotekę java Math, może pomoże nam w porządkach :)

2021-09-05 19:32 UTC, mtszpater approved these changes

2021-09-10 10:57 UTC, merged